// <auto-generated />
using System;
using GSDrones.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace gs_drones_dotnet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250608030101_DroneEntidade")]
    partial class DroneEntidade
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GSDrones.Models.Drone", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("CapacidadeKg")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("nr_capacidade_kg");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("nm_drone");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("NVARCHAR2(12)")
                        .HasColumnName("tp_drone");

                    b.HasKey("Id");

                    b.ToTable("t_gs_drones", (string)null);
                });

            modelBuilder.Entity("GSDrones.Models.Missao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_fim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_inicio");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("ds_missao");

                    b.Property<long>("DroneId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<double>("PesoTotal")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("nr_peso_total");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("st_missao");

                    b.HasKey("Id");

                    b.HasIndex("DroneId");

                    b.ToTable("Missoes");
                });

            modelBuilder.Entity("GSDrones.Models.Suprimento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("ds_suprimento");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("nm_suprimento");

                    b.Property<double>("PesoKg")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("peso_kg");

                    b.HasKey("Id");

                    b.ToTable("Suprimentos");
                });

            modelBuilder.Entity("GSDrones.Models.SuprimentoMissao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("MissaoId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("qt_suprimento");

                    b.Property<long>("SuprimentoId")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("Id");

                    b.HasIndex("MissaoId");

                    b.HasIndex("SuprimentoId");

                    b.ToTable("SuprimentosMissoes");
                });

            modelBuilder.Entity("GSDrones.Models.Missao", b =>
                {
                    b.HasOne("GSDrones.Models.Drone", "Drone")
                        .WithMany("Missoes")
                        .HasForeignKey("DroneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drone");
                });

            modelBuilder.Entity("GSDrones.Models.SuprimentoMissao", b =>
                {
                    b.HasOne("GSDrones.Models.Missao", "Missao")
                        .WithMany("Suprimentos")
                        .HasForeignKey("MissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GSDrones.Models.Suprimento", "Suprimento")
                        .WithMany("Missoes")
                        .HasForeignKey("SuprimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Missao");

                    b.Navigation("Suprimento");
                });

            modelBuilder.Entity("GSDrones.Models.Drone", b =>
                {
                    b.Navigation("Missoes");
                });

            modelBuilder.Entity("GSDrones.Models.Missao", b =>
                {
                    b.Navigation("Suprimentos");
                });

            modelBuilder.Entity("GSDrones.Models.Suprimento", b =>
                {
                    b.Navigation("Missoes");
                });
#pragma warning restore 612, 618
        }
    }
}
